version: "3.2"
services:
#  the-back-forge:
#   image: the-back-forge
#    volumes:
#      - "/e/DEV/test/TheOneForge/TheOneBackForge:/usr/src/app"
#    links:
#      - neo4j
#    ports:
#      - "3000:3000"

  neo4j:
    image: neo4j:3.5
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
